# -*- coding: utf-8 -*-
# """END TO END RAG CHATBOT.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1sO7F3eEP8oBUhDJoJSYk1kLR647TrEAR
# """

# pip install langchain-community

# pip install langchain_text_splitters
import streamlit as st

import os

# pip install pymupdf

from langchain_community.document_loaders import PyMuPDFLoader

doc = PyMuPDFLoader("DSML.pdf")
docs = doc.load()

len(docs)


# FOR CHUNKING I USE THE SPILTTER

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size = 1000, chunk_overlap= 200)

splitted_data = splitter.split_documents(docs)

len(splitted_data)

# """step3--------EMBADDING--------"""

# embadding technique

# !pip install langchain-huggingface

# import streamlit as st

from langchain_huggingface import HuggingFaceEmbeddings

@st.cache_resource
def create_vector_store():
    return FAISS.from_documents(
        documents=splitted_data,
        embedding=embeddings
    )

vector_store = create_vector_store()
embeddings = load_embeddings()

# """PHASE 4 -----FAISS VECTOR DB-----"""

# pip install langchain_faiss

# pip install faiss-cpu

from langchain_community.vectorstores import FAISS

@st.cache_resource
def create_vector_store():
    return FAISS.from_documents(
        documents=splitted_data,
        embedding=embeddings
    )


# !pip install -U langchain-google-genai google-generativeai

from langchain_google_genai import ChatGoogleGenerativeAI

from langchain_groq import ChatGroq

llm = ChatGroq(
    groq_api_key=st.secrets["GROQ_API_KEY"],
    model_name="llama-3.3-70b-versatile"
)

# result = llm.invoke("What is Machine Learning?")

# print(result.content)

# now connection or creating chain for all the phases

# retriever = vector_store.as_retriever(
#     search_kwargs={"k": 5}
# )
# this will give me the top 5 chunks

def get_context(query: str):

    data = vector_store.similarity_search(
        query=query,
        k=5
    )

    # print(f"Retrieved Chunks: {len(data)}")

    context = "\n\n".join(
        [doc.page_content for doc in data]
    )

    return {
        "context": context,
        "question": query
    }

from langchain_core.prompts import PromptTemplate

prompt_template = """
You are a helpful assistant.

Answer the question using ONLY the provided context.

Provide a detailed answer.
Use all relevant information from the context.
Do not give a one-line summary unless the context itself is very short.

If the answer is not present in the context, respond exactly with:

"I could not find this information in the provided document."

Context:
{context}

Question:
{question}

Answer:
"""

PROMPT = PromptTemplate(
    template=prompt_template,
    input_variables=["context", "question"]
)

rag_chain = get_context | PROMPT | llm

# streamlit

# pip install streamlit

# import streamlit as st

st.title("RAG BASED CHATBOT FOR DATA SCIENTIST")

st.markdown(
    "## DATA SCIENCE CHATBOT"
)

query = st.chat_input(
    "Ask Anything?"
)

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:

    st.chat_message(
        message["role"]
    ).markdown(
        message["content"]
    )

if query:

    st.session_state.messages.append(
        {"role":"user","content":query}
    )

    st.chat_message("user").markdown(query)

    query_lower = query.lower().strip()

    if query_lower in ["hi", "hello", "hey", "hii"]:

        response = (
            "Hello! I am a Data Science PDF Chatbot. "
            "Ask me anything about the document."
        )

    else:

         with st.spinner("Thinking..."):

        try:
            response = rag_chain.invoke(query).content

        except Exception as e:
            response = f"Error: {str(e)}"

    st.session_state.messages.append(
        {
            "role":"assistant",
            "content":response




