# -*- coding: utf-8 -*-
"""END TO END RAG CHATBOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sO7F3eEP8oBUhDJoJSYk1kLR647TrEAR
"""

# pip install langchain-community

# pip install langchain_text_splitters

import os

pip install pymupdf

from langchain_community.document_loaders import PyMuPDFLoader

doc = PyMuPDFLoader("/content/DSML.pdf")

docs = doc.load()

len(docs)

"""step 2 ---------CHUNKING------"""

# FOR CHUNKING I USE THE SPILTTER

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size = 3000, chunk_overlap= 500)

splitted_data = splitter.split_documents(docs)

len(splitted_data)

"""step3--------EMBADDING--------"""

# embadding technique

# !pip install langchain-huggingface
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-small-en-v1.5"
)

"""PHASE 4 -----FAISS VECTOR DB-----"""

# pip install langchain_faiss

# pip install faiss-cpu

from langchain_community.vectorstores import FAISS

vector_store = FAISS.from_documents(
    documents= splitted_data,
    embedding = embeddings
)

"""  PHASE 5 ------LLM MODEL-------"""

from google.colab import userdata
api_key=userdata.get('GEMINI_API_KEY')

# !pip install -U langchain-google-genai google-generativeai

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash",
    google_api_key= api_key
)

result = llm.invoke("What is Machine Learning?")

print(result.content)

# now connection or creating chain for all the phases

# retriever = vector_store.as_retriever(
#     search_kwargs={"k": 5}
# )
# this will give me the top 5 chunks

def get_context(query: str):

    data = vector_store.similarity_search(
        query=query,
        k=10
    )

    print(f"Retrieved Chunks: {len(data)}")

    context = "\n\n".join(
        [doc.page_content for doc in data]
    )

    return {
        "context": context,
        "question": query
    }

from langchain_core.prompts import PromptTemplate

prompt_template = """
You are a helpful assistant.

Answer the question using ONLY the provided context.

Provide a detailed answer.
Use all relevant information from the context.
Do not give a one-line summary unless the context itself is very short.

If the answer is not present in the context, respond exactly with:

"I could not find this information in the provided document."

Context:
{context}

Question:
{question}

Answer:
"""

PROMPT = PromptTemplate(
    template=prompt_template,
    input_variables=["context", "question"]
)

rag_chain = get_context | PROMPT | llm

res = rag_chain.invoke(
    "What is ritik?"
)

print(res.content)

# streamlit

# pip install streamlit

import streamlit as st

st.title("RAG BASED CHATBOT FOR DATA SCIENTIST")

st.markdown(
    "## DATA SCIENCE CHATBOT"
)

query = st.chat_input(
    "Ask Anything?"
)

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:

    st.chat_message(
        message["role"]
    ).markdown(
        message["content"]
    )

if query:

    st.session_state.messages.append(
        {"role":"user","content":query}
    )

    st.chat_message("user").markdown(query)

    with st.spinner("Thinking..."):

        res = rag_chain.invoke(query)

    st.session_state.messages.append(
        {
            "role":"assistant",
            "content":res.content
        }
    )

    st.chat_message("assistant").markdown(
        res.content
    )





